"""Phase 5 audit registry for proposed GNN troubled-cell features."""

from __future__ import annotations


DISPOSITIONS = {"adopt", "test", "defer", "reject"}


def item(
    suggestion_id,
    suggestion,
    category,
    status,
    overlap,
    evidence,
    dependencies,
    experiment,
    priority,
    disposition,
    experiment_id=None,
):
    return {
        "suggestion_id": suggestion_id,
        "suggestion": suggestion,
        "category": category,
        "current_implementation_status": status,
        "overlap_with_phases_2_3": overlap,
        "supporting_or_contrary_evidence": evidence,
        "dependencies": dependencies,
        "proposed_controlled_experiment": experiment,
        "scheduled_experiment_id": experiment_id,
        "priority": priority,
        "disposition": disposition,
    }


SUGGESTIONS = [
    item(
        "node-invariant-statistics",
        "Permutation-invariant P1 mean, standard deviation, and range",
        "scalar node representation",
        "implemented in invariant-node-v2 and both edge-aware schemas",
        "Directly tested in Phase 3 against ordered-global-v1.",
        "F1 rose from 0.3716 to 0.5414 and permutation differences became exactly zero.",
        [],
        "Retain in the primary representation and all compatible future scalar controls.",
        "critical",
        "adopt",
    ),
    item(
        "node-gradient-magnitude",
        "Dimensionless physical gradient magnitude h|grad u|/s",
        "scalar node representation",
        "implemented in invariant-node-v2 and both edge-aware schemas",
        "Bundled with invariant node statistics in Phase 3; not isolated alone.",
        "The invariant node bundle improved offline/selectivity results, but the gradient term has no independent effect estimate.",
        [],
        "Retain as part of the primary node bundle; isolate only if feature attribution later motivates removal.",
        "high",
        "adopt",
    ),
    item(
        "node-local-extremum-ratios",
        "Local-extremum ratios relative to face neighbors",
        "scalar node representation",
        "implemented and completed as invariant-extrema-v3 / P5-LOCAL-EXTREMA-001",
        "Added two bounded envelope-violation features to invariant-node-v2 with all other factors fixed.",
        "F1/PR-AUC improved to 0.5818/0.7284 and flags fell to 32.99%, but calibration undershoot 0.01418 still failed the 0.01 rule.",
        ["fixed invariant-node-v2 control", "one-factor schema extension"],
        "Completed; retain runs/feature-review/p5-local-extrema-summary.json as a partial/negative result.",
        "not-applicable",
        "reject",
        "P5-LOCAL-EXTREMA-001",
    ),
    item(
        "node-local-robust-scale",
        "One-ring MAD/max-jump robust normalization",
        "normalization",
        "implemented in invariant-local-v2",
        "Directly tested after adding invariant nodes and edges in Phase 3.",
        "Offline F1 reached 0.7252 and mean flags 9.75%, but worst calibration/held-out undershoots were 0.2062/0.2257.",
        [],
        "Do not use the Phase 3 local-scale definition as the primary normalization; any replacement needs a newly specified bounded hybrid scale.",
        "not-applicable",
        "reject",
    ),
    item(
        "node-hybrid-scale",
        "Bounded hybrid of global and local normalization",
        "normalization",
        "not implemented",
        "Motivated by the contrary local-scale result in Phase 3.",
        "Global scaling is conservative but nonlocal; pure local scaling is predictive but unsafe.",
        ["predeclared interpolation/cap", "invariant-node-v2 control"],
        "Cap local normalization relative to the fixed global scale and vary only the cap in a calibration-only pilot before five-seed evaluation.",
        "medium",
        "test",
        "P5-HYBRID-SCALE-001",
    ),
    item(
        "node-relative-area",
        "Log area relative to the one-ring median area",
        "mesh geometry",
        "implemented in all invariant schemas",
        "Included in the Phase 3 invariant node bundle.",
        "No independent effect estimate; it is dimensionless and permutation invariant.",
        [],
        "Retain for mesh-transfer experiments.",
        "medium",
        "adopt",
    ),
    item(
        "node-shape-quality",
        "Bounded triangle radius-ratio quality",
        "mesh geometry",
        "implemented in all invariant schemas",
        "Included in the Phase 3 invariant node bundle.",
        "No independent effect estimate; Delaunay and structured held-out rows both completed.",
        [],
        "Retain while testing broader mesh-quality distributions.",
        "medium",
        "adopt",
    ),
    item(
        "node-boundary-neighbor-fractions",
        "Boundary-face and interior-neighbor fractions",
        "mesh geometry",
        "implemented in all invariant schemas",
        "Included in the Phase 3 invariant node bundle.",
        "Periodic rotation meshes do not isolate physical boundary-condition semantics.",
        [],
        "Retain as topology features; test boundary types separately.",
        "medium",
        "adopt",
    ),
    item(
        "edge-mean-jump",
        "Directed normalized jump in neighboring cell means",
        "scalar edge representation",
        "implemented in invariant-edge-v2 and invariant-local-v2",
        "Added with the complete six-dimensional edge bundle in Phase 3.",
        "Edge bundle changed F1 only from 0.5414 to 0.5427 and raised mean runtime from 15.57 s to 20.18 s.",
        [],
        "Do not adopt the tested edge bundle by default; reuse its infrastructure for directional experiments.",
        "low",
        "reject",
    ),
    item(
        "edge-face-trace-jumps",
        "Directed mean and maximum P1 face-trace jumps",
        "scalar edge representation",
        "implemented in invariant-edge-v2 and invariant-local-v2",
        "Added with the complete six-dimensional edge bundle in Phase 3.",
        "The standalone edge bundle gave only marginal offline/selectivity gains.",
        ["edge-aware GAT infrastructure already implemented"],
        "Retain as a control when flow direction or classical sensor fusion is tested, not as an adopted standalone addition.",
        "medium",
        "defer",
        "P5-FLOW-CFL-001",
    ),
    item(
        "edge-normal-gradient-jump",
        "Directed normal-gradient jump",
        "scalar edge representation",
        "implemented in invariant-edge-v2 and invariant-local-v2",
        "Added with the complete six-dimensional edge bundle in Phase 3.",
        "No independent benefit was established because the edge components were bundled.",
        [],
        "Keep available for later feature-pruning, but do not promote independently.",
        "low",
        "defer",
    ),
    item(
        "edge-face-geometry",
        "Relative face length and centroid distance",
        "mesh geometry",
        "implemented in invariant-edge-v2 and invariant-local-v2",
        "Added with the complete six-dimensional edge bundle in Phase 3.",
        "No independent benefit was established; quantities are dimensionless and stable.",
        ["an edge-aware schema"],
        "Retain when an accepted directional edge experiment requires edge geometry.",
        "low",
        "defer",
    ),
    item(
        "edge-rotation-aware-normal",
        "Rotation-aware or equivariant face-normal encoding",
        "directional geometry",
        "not implemented",
        "Explicitly excluded from Phase 3.",
        "Phase 3 proves scalar invariance but provides no evidence for directional equivariance.",
        ["equivariant architecture or local-frame design", "rotation stress protocol"],
        "Compare scalar a.n features with a rigorously equivariant normal encoding after the simple flow experiment.",
        "low",
        "defer",
        "P5-EQUIVARIANT-001",
    ),
    item(
        "edge-flow-direction",
        "Normal advection speed and inflow/outflow sign",
        "PDE context",
        "not implemented",
        "Explicitly excluded from Phase 3; KXRCF already computes inflow faces.",
        "The undirected edge bundle was marginal, so direction is the next clean hypothesis for making edge features useful.",
        ["variable-velocity data", "raw invariant-node-v2 control", "edge-aware control"],
        "Add only a.n and inflow sign to the tested edge schema, with rotations and reversed flow included in held-out cases.",
        "high",
        "test",
        "P5-FLOW-CFL-001",
    ),
    item(
        "edge-local-cfl",
        "Local CFL or spectral-radius-times-dt/h feature",
        "PDE context",
        "not implemented",
        "Explicitly excluded from Phase 3.",
        "No current evidence; all Phase 3 inference used one solver protocol.",
        ["time-step context passed into indicator", "flow-direction control"],
        "Add local CFL only after the flow-direction factor is measured.",
        "medium",
        "defer",
        "P5-FLOW-CFL-002",
    ),
    item(
        "edge-boundary-condition-type",
        "Boundary-condition edge type",
        "boundary context",
        "not implemented; graph contains interior edges only",
        "Phase 3 used periodic scalar rotation and did not isolate boundary behavior.",
        "No supporting controlled evidence.",
        ["explicit boundary graph edges", "multi-boundary training/evaluation data"],
        "Add boundary nodes/edges only for a benchmark suite containing reflective, inflow, outflow, and periodic boundaries.",
        "low",
        "defer",
        "P5-BOUNDARY-001",
    ),
    item(
        "node-gradient-direction",
        "Physical gradient direction or components",
        "directional node representation",
        "not implemented; only magnitude is present",
        "Explicitly omitted from the invariant Phase 3 schemas.",
        "Raw components would break rotation invariance without a local frame or equivariant model.",
        ["flow direction", "rotation-aware encoding"],
        "Test only in a flow-aligned local frame alongside P5-FLOW-CFL-001.",
        "low",
        "defer",
    ),
    item(
        "higher-order-modal-energy",
        "Modal energy by degree and Persson highest-mode ratio",
        "higher polynomial order",
        "not implemented; solver study is fixed P1",
        "Correctly excluded from Phase 3 because a P1 highest-mode ratio is too limited.",
        "No P>1 controlled evidence exists.",
        ["P2/P3 triangular DG data and solver", "degree-aware feature schema"],
        "Evaluate only after a higher-order solver/data protocol is frozen.",
        "low",
        "defer",
        "P5-HIGHER-ORDER-001",
    ),
    item(
        "classical-sensor-fusion",
        "Continuous KXRCF/minmod/Barth-Jespersen sensor values as inputs",
        "sensor fusion",
        "not implemented",
        "Phase 3 tested raw invariant and edge features only.",
        "KXRCF alone has large rotation undershoots; fusion may help but must include a raw-feature control.",
        ["continuous sensor API", "raw invariant-node-v2 control", "one sensor per experiment"],
        "Start with one continuous KXRCF magnitude and compare against both raw GNN and hard OR safety net.",
        "high",
        "test",
        "P5-SENSOR-FUSION-001",
    ),
    item(
        "classical-or-safety-net",
        "Hard GNN OR KXRCF safety net",
        "solver safety",
        "completed as P5-SAFETY-OR-001",
        "Used the frozen Phase 4 primary rows and ran 60 new bounded KXRCF/union cases without retraining.",
        "The union passed calibration safety (maximum undershoot 0.00849) and accuracy guards, but failed selectivity with 62.71% mean held-out flagging.",
        ["five primary checkpoints", "frozen GNN/KXRCF thresholds"],
        "Completed; retain runs/feature-review/p5-safety-or-summary.json as a negative overall acceptance result.",
        "not-applicable",
        "reject",
        "P5-SAFETY-OR-001",
    ),
    item(
        "cell-semidiscrete-residual",
        "Cell residual normalized by wave speed and volume",
        "solver-aware static context",
        "not implemented",
        "Not part of Phase 3 static exact-field data.",
        "Potentially informative but changes data generation and inference cost.",
        ["residual extraction API", "numerical-stage training data"],
        "Test as a single static feature before any recurrent history.",
        "medium",
        "defer",
        "P5-RESIDUAL-001",
    ),
    item(
        "euler-primitive-cells",
        "Locally normalized density, pressure, velocity, sound speed, Mach, and entropy",
        "Euler node representation",
        "not implemented",
        "Scalar Phase 3 schemas cannot support an Euler learned-indicator claim.",
        "The Euler solver is feasible, but no Euler-aware checkpoint has been trained/evaluated.",
        ["Euler stage-state data", "nondimensionalization", "multi-problem split"],
        "Build a primitive-feature baseline before characteristic edges.",
        "medium",
        "defer",
        "P5-EULER-PRIMITIVE-001",
    ),
    item(
        "euler-characteristic-faces",
        "Face-normal characteristic jumps, compression, and Rankine-Hugoniot residual",
        "Euler edge representation",
        "not implemented",
        "Explicitly excluded from Phase 3.",
        "No Euler-aware baseline exists, so the incremental value cannot yet be isolated.",
        ["P5-EULER-PRIMITIVE-001", "face-normal eigensystem"],
        "Add characteristic jumps only after the primitive node baseline is frozen.",
        "low",
        "defer",
        "P5-EULER-CHAR-001",
    ),
    item(
        "euler-positivity-flux-features",
        "Positivity margins, local spectral radius, and LLF dissipation",
        "Euler solver context",
        "solver quantities exist but are not GNN features",
        "Euler positivity scaling and LLF flux are implemented outside the learned indicator.",
        "No controlled learned Euler evidence exists.",
        ["P5-EULER-PRIMITIVE-001", "feature extraction without label leakage"],
        "Add one feature family at a time after the primitive baseline.",
        "low",
        "defer",
        "P5-EULER-POSITIVITY-001",
    ),
    item(
        "history-stage-change",
        "Previous-stage/timestep change in cell mean",
        "dynamic features",
        "not implemented",
        "Explicitly deferred until after static Phase 3 features.",
        "No evidence yet; makes the detector stateful.",
        ["trajectory dataset", "state reset/restart semantics"],
        "Test one-step residual/change before longer history.",
        "low",
        "defer",
        "P5-HISTORY-001",
    ),
    item(
        "history-previous-decision",
        "Previous detector probability, limiter coefficient, or consecutive-flag count",
        "dynamic features",
        "not implemented",
        "Explicitly deferred until after static Phase 3 features.",
        "May create feedback/hysteresis and complicate restart reproducibility.",
        ["P5-HISTORY-001", "stateful inference protocol"],
        "Evaluate hysteresis and restart equivalence as mandatory stress tests.",
        "low",
        "defer",
        "P5-HISTORY-002",
    ),
    item(
        "labels-soft-distance",
        "Soft distance-to-discontinuity labels",
        "labels and objective",
        "not implemented",
        "Phase 2/3 retain exact binary geometric labels.",
        "Local scaling's high F1 but poor safety shows that offline labels/metrics do not guarantee downstream robustness.",
        ["fixed invariant-node-v2 features", "distance calibration definition"],
        "Compare binary labels with one predeclared distance kernel using identical data and seeds.",
        "medium",
        "test",
        "P5-LABEL-SAFETY-002",
    ),
    item(
        "labels-one-cell-halo",
        "One-cell safety halo around positive labels",
        "labels and objective",
        "implemented and completed as P5-LABEL-SAFETY-001",
        "Changed only the training targets; validation labels, invariant-node-v2 features, data/split IDs, seeds, and solver protocol remained fixed.",
        "Recall rose to 0.8830, but PR-AUC fell to 0.5360, calibration undershoot exceeded 0.01, and held-out cases exceeded the runtime budget.",
        ["fixed invariant-node-v2 features", "same five seeds"],
        "Completed; retain runs/feature-review/p5-label-halo-summary.json as a negative label-policy result.",
        "not-applicable",
        "reject",
        "P5-LABEL-SAFETY-001",
    ),
    item(
        "objective-cost-sensitive-fn",
        "Cost-sensitive false-negative weighting",
        "labels and objective",
        "not implemented for the GNN binary-cross-entropy objective",
        "Phase 3 selects checkpoints by F1 and thresholds by downstream bounds.",
        "The primary narrowly misses calibration safety, suggesting recall cost deserves a controlled test.",
        ["fixed invariant-node-v2 features", "predeclared weight grid on validation only"],
        "Vary only the positive/false-negative cost after the halo-label experiment.",
        "high",
        "test",
        "P5-LABEL-SAFETY-003",
    ),
    item(
        "objective-downstream-aware",
        "Differentiable loss penalizing oscillation and excessive limiting",
        "labels and objective",
        "not implemented",
        "Phase 3 reports solver metrics but does not train through the solver.",
        "Attractive but materially more complex and easy to confound with feature changes.",
        ["differentiable surrogate or rollout", "stable compute budget", "fixed feature baseline"],
        "Attempt only after label and cost-sensitive controls fail.",
        "low",
        "defer",
        "P5-DOWNSTREAM-LOSS-001",
    ),
    item(
        "architecture-depth-family",
        "GAT depth and GCN/SAGE architecture sweep",
        "architecture",
        "GAT/GCN/SAGE implementations exist; no controlled Phase 3 sweep",
        "Phase 3 deliberately fixed architecture capacity.",
        "Feature results should not be attributed to an architecture change; no need is established yet.",
        ["accepted feature/label baseline", "matched parameter counts"],
        "Run only after safety-oriented feature and label experiments.",
        "low",
        "defer",
        "P5-ARCH-001",
    ),
]


def validate_suggestions(rows=SUGGESTIONS):
    required = {
        "suggestion_id",
        "suggestion",
        "category",
        "current_implementation_status",
        "overlap_with_phases_2_3",
        "supporting_or_contrary_evidence",
        "dependencies",
        "proposed_controlled_experiment",
        "scheduled_experiment_id",
        "priority",
        "disposition",
    }
    ids = [row["suggestion_id"] for row in rows]
    if len(ids) != len(set(ids)):
        raise ValueError("feature-review suggestion IDs must be unique")
    for row in rows:
        missing = required - row.keys()
        if missing:
            raise ValueError(f"{row.get('suggestion_id')} is missing {sorted(missing)}")
        if row["disposition"] not in DISPOSITIONS:
            raise ValueError(f"invalid disposition for {row['suggestion_id']}")
        if row["disposition"] == "test" and not row["scheduled_experiment_id"]:
            raise ValueError(f"test item {row['suggestion_id']} lacks an experiment ID")
    return True
